# Generated by Django 4.1.6 on 2023-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.CharField(max_length=100, verbose_name='Филиал в городе')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('employees_num', models.PositiveIntegerField(verbose_name='Количество сотрудников')),
                ('branches_num', models.PositiveIntegerField(verbose_name='Количество филиалов')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.RenameField(
            model_name='person',
            old_name='cooker',
            new_name='chef',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='salery',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=2, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='place_1',
            field=models.BooleanField(default=False, verbose_name='На складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='place_2',
            field=models.BooleanField(default=False, verbose_name='В магазине'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
