# Generated by Django 4.1.6 on 2023-02-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_branches_rename_cooker_person_chef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='branches_num',
        ),
    ]
